services:
  mongodb:
    image: mongo:7.0
    container_name: praja-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: praja-collections
    volumes:
      - mongodb-data:/data/db
    networks:
      - praja-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAZORPAY_KEY_ID: rzp_test_Suk6oqJ6pDpYWe
        RAZORPAY_KEY_SECRET: 92QN8XqolzX3P7DVwyg62sl9
    container_name: praja-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/praja-collections
      - NEXTAUTH_SECRET=praja-collections-secret-key-2025
      - NEXTAUTH_URL=http://localhost:3000
      - RAZORPAY_KEY_ID=rzp_test_Suk6oqJ6pDpYWe
      - RAZORPAY_KEY_SECRET=92QN8XqolzX3P7DVwyg62sl9
    depends_on:
      - mongodb
    networks:
      - praja-network

networks:
  praja-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
